[package]
name = "rust_ble"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
btleplug = "0.11.5"
futures = "0.3.30"
pretty_env_logger = "0.5.0"
tokio = { version = "1.39.3", features = ["full"] }
uuid = "1.10.0"
